Fixed a typo in openscenario_parser.py
carla-simulator/scenario_runner pull request #1118
Opened 2024-10-15 11:34 UTC by dx6nxr

#### Description

There was a typo in function "get_traffic_light_from_osc_name" in openscenario_parser.py, which was trying to access "CCarlaDataProvider" insted of "CarlaDataProvider". Typo fixed.

This is the typo.
![image](https://github.com/user-attachments/assets/66ee222f-5c26-488a-aa88-a49f7febf9ef)
Runs without problems after fixing the typo.

#### Where has this been tested?

  * **Platform(s):** Win11
  * **Python version(s):** 3.8.10
  * **CARLA version:** 0.9.15

#### Possible Drawbacks

None.

2024-10-20 10:06 UTC, Daraan requested changes
I've spotted this a while ago as well (and forgot about it) I wondered more strongly why is this code not executed which would reveal the error, but it seems you have a setup that takes this conditional path.

2024-10-20 10:06 UTC, Daraan commented on result
I think you introduced a new file here by accident.

2024-10-21 09:41 UTC, dx6nxr reviewed
The "results" file is removed.

2024-10-21 09:41 UTC, dx6nxr commented on result
Hey, yes indeed I did. Pushed a new commit deleting this file 👍🏿

2024-10-21 09:45 UTC, dx6nxr commented
> I've spotted this a while ago as well (and forgot about it) I wondered more strongly why is this code not executed which would reveal the error, but it seems you have a setup that takes this conditional path.

As there are two options for traffic lights, either they have id's in the .xodr file (which is id="" option), and Carla ones, where the traffic light is being obtained by its coordinates (pos=x,y). The test suite probably does not cover the Carla maps and therefore the Varla traffic light representation via the coordinates. For me the traffic lights worked without problems after this change.

Best,
Ivan

2024-10-21 09:49 UTC, Daraan approved these changes

2024-10-21 09:53 UTC, Daraan commented
I am sadly no maintainer, but hopefully @PabloVD can merge this typo fix asap.

2024-10-21 10:42 UTC, PabloVD approved these changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1118)* status: all files reviewed, 1 unresolved discussion (waiting on @Daraan)



<!-- Sent from Reviewable.io -->

2024-10-21 10:46 UTC, PabloVD approved these changes
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1118)* status: all files reviewed, 1 unresolved discussion (waiting on @Daraan)



<!-- Sent from Reviewable.io -->

2024-10-21 10:50 UTC, glopezdiest approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1118#-:-O9igdIpDQLY919C1ctz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Daraan)



<!-- Sent from Reviewable.io -->

2024-10-21 10:52 UTC, PabloVD commented
Thank you both for spotting this!
@Daraan seems that you are blocking merging the PR with the unresolved discussion, can you resolve it so we can proceed?

2024-10-21 13:00 UTC, Daraan reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Took me a bit to realize it is on Reviewable. Hope it is fine now.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1118#-:-O9j96VNDlQgHZV_QRuJ:bjr8krg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dx6nxr)



<!-- Sent from Reviewable.io -->

2024-10-21 14:02 UTC, dx6nxr commented
> <img alt=":lgtm:" width="61" height="20" src="https://camo.githubusercontent.com/204e5a43dbe1a0ce96b00dc9f6efaa7c31943c30f6d7fc9f92fa23ad865d6ea0/68747470733a2f2f72657669657761626c652e696f2f6c67746d2e706e67"> Took me a bit to realize it is on Reviewable. Hope it is fine now.
> 
> > Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/1118#-:-O9j96VNDlQgHZV_QRuJ:bjr8krg)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dx6nxr)

Didn't know that I have to review it too, sorry, took some time. Should be fine now.

2024-10-21 14:04 UTC, Daraan commented
> Didn't know that I have to review it too, sorry, took some time. Should be fine now.

I do not think you have to; Reviewable just automatically tags you in the message it generates.

2024-10-21 14:36 UTC, merged

2024-10-21 14:36 UTC, PabloVD commented
Merged, thank you both again!