Yield to emergency vehicle
carla-simulator/scenario_runner pull request #891
Opened 2022-05-09 08:18 UTC by TayYim

#### Description

Add YieldToEmergencyVehicle scenario. Along with WaitForTime(AtomicCondition) and YieldToEmergencyVehicleTest(Criterion).

Fixes #  

#### Where has this been tested?

  * **Platform(s):** Ubuntu 20.04
  * **Python version(s):** 3.7
  * **Unreal Engine version(s):** 4.26
  * **CARLA version:** leaderboard-2.0 branch

#### Possible Drawbacks

2022-05-09 08:58 UTC, glopezdiest requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 1 of 4 files reviewed, 9 unresolved discussions (waiting on @glopezdiest and @TayYim)

___
*[`srunner/routes/YieldToEmergencyVehicle.xml` line 2 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1byadD06E4eqvlzVtI:-N1byadE-3lpkBC_SJdv:b-t6bm4v) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/routes/YieldToEmergencyVehicle.xml#L2)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> <routes>
> ```

I changed this. Please add this route to the leaderboard_2.0_testing.xml file instead. In that way, all testing rotues are at the same file, and we can more easily remove them later on. Just make sure the id doesn't match the other routes



_Code quote:_
```XML
<routes>
```
___
*[`srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py` line 1289 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1bz3v56m8lNFxZmeMS:-N1bz3v56m8lNFxZmeMT:b-5ftdje) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py#L1289)):*
> ```Python
>         return new_status
> 
> class WaitForTime(AtomicCondition):
> ```

Not needed, we already have the atomic behavior Idle()



_Code quote:_
```Python
class WaitForTime(AtomicCondition):
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 45 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1bzCdCE35FhJjVNX8O:-N1bzCdCE35FhJjVNX8P:b-suirqp) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L45)):*
> ```Python
>         self._map = CarlaDataProvider.get_map()
>         self.timeout = timeout
>         self._actor_types = ["vehicle.carlamotors.firetruck", "vehicle.ford.ambulance",
> ```

Not needed, when spawning the actor, you can check for the 'special_type': 'emergency', which will automatically filter those 4 blueprints



_Code quote:_
```Python
self._actor_types 
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 48 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1bzn8U7vkQGIC9oqxn:-N1bzn8U7vkQGIC9oqxo:b-jedbwz) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L48)):*
> ```Python
>                              "vehicle.dodge.charger_police", "vehicle.dodge.charger_police_2020"]
>         self._ev_drive_time = 20  # seconds
>         self._ev_speed = 80
> ```

This should be a behavior such that the EV goes at a set speed higher than the ego. If the ego goes at 100 Km/h, the EV will never catch up to it



_Code quote:_
```Python
self._ev_speed = 80
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 82 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c-p_C-uh2ZwNBtk7F:-N1c-p_D8Lvy2Wzgwd3-:b-d5u0bg) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L82)):*
> ```Python
>                 "Couldn't spawn the emergency vehicle")
>         self.other_actors.append(actor)
> ```

Remove the physics of the EV so that it doesn't fall (which will eventually break Unreal)
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 103 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c-At_EedV1czSE_Lt:-N1c-At_EedV1czSE_Lu:bku0lu7) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L103)):*
> ```Python
> 
>         # Teleport EV behind the ego
>         ev_points = self._map.get_waypoint(self.ego_vehicles[0].get_location()).previous(
> ```

As I said in a previous review, don't use the ego's position, use the trigger point instead. Also, in general, what we do about the spawning is:
- Make sure the spawn position is correct by spawning the ego there
- Move the EV below ground
- Use an ActorTransformSetter to teleport it back to the spawn position
Not saying your approach is incorrect though, I haven't tested it



_Code quote:_
```Python
        ev_points = self._map.get_waypoint(self.ego_vehicles[0].get_location()).previous(
            self._emergency_vehicle_distance)
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 113 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c0iqb5tG_GkgL8i2u:-N1c0iqcEz8h_IguQzip:b-itn1c8) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L113)):*
> ```Python
>             self.other_actors[0], ev_start_transform))
> 
>         sequence.add_child(SwitchOutsideRouteLanesTest(False))
> ```

Is this needed? Do we expect this from the ego?



_Code quote:_
```Python
sequence.add_child(SwitchOutsideRouteLanesTest(False))
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 121 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c1AHpDqpyfFOhthyh:-N1c1AHpDqpyfFOhthyi:b-4jfl5l) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L121)):*
> ```Python
>         ev_end_condition.add_child(WaitForTime(self._ev_drive_time))
> 
>         ev_end_condition.add_child(WaypointFollower(
> ```

Does this condition start with the vehicle stopped?

I'd also recommend using the BasicAgentBehavior or the ConstantVelocityAgentBehavior, which is the more flexible Python agents 



_Code quote:_
```Python
        ev_end_condition.add_child(WaypointFollower(
            self.other_actors[0], self._ev_speed, avoid_collision=True))
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 146 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c1Xeg6urVSd758cTx:-N1c1Xeg6urVSd758cTy:bros87k) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L146)):*
> ```Python
>         in parallel behavior tree.
>         """
>         if self.route_mode:
> ```

This code is correct, but weird



_Code quote:_
```Python
        if self.route_mode:
            return[YieldToEmergencyVehicleTest(self.ego_vehicles[0], self.other_actors[0])]

        return [CollisionTest(self.ego_vehicles[0]), YieldToEmergencyVehicleTest(self.ego_vehicles[0], self.other_actors[0])]
```


<!-- Sent from Reviewable.io -->

2022-05-11 08:20 UTC, TayYim reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 0 of 5 files reviewed, 9 unresolved discussions (waiting on @glopezdiest)

___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 45 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1bzCdCE35FhJjVNX8O:-N1mAbaa8qznBTk1nSsT:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L45)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Not needed, when spawning the actor, you can check for the 'special_type': 'emergency', which will automatically filter those 4 blueprints
</blockquote></details>

Done.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 48 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1bzn8U7vkQGIC9oqxn:-N1mAvdYDEO_pjEPPK1n:ba09c8k) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L48)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This should be a behavior such that the EV goes at a set speed higher than the ego. If the ego goes at 100 Km/h, the EV will never catch up to it
</blockquote></details>

This is removed. Using BasicAgentBehavior. See below
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 82 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c-p_C-uh2ZwNBtk7F:-N1mB2oLArNaRmvIv-rp:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L82)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Remove the physics of the EV so that it doesn't fall (which will eventually break Unreal)
</blockquote></details>

Done.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 103 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c-At_EedV1czSE_Lt:-N1mBCMFBGyu4GWw8P2w:bmr8ftm) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L103)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

As I said in a previous review, don't use the ego's position, use the trigger point instead. Also, in general, what we do about the spawning is:
- Make sure the spawn position is correct by spawning the ego there
- Move the EV below ground
- Use an ActorTransformSetter to teleport it back to the spawn position
Not saying your approach is incorrect though, I haven't tested it
</blockquote></details>

Use trigger point as the reference waypoint when teleporting the EV(ev_start_transform). 
Do you mean it’s better to first spawn ev on  ev_start_transform, then move it underground, then teleport it back to ev_start_transform when the scenario is triggered?
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 113 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c0iqb5tG_GkgL8i2u:-N1mBIdO7kIJCPJEA1rn:b-t5byu6) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L113)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Is this needed? Do we expect this from the ego?
</blockquote></details>

Remove the switch of OutsideRouteLanesTest. I had some misunderstanding of it before
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 121 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c1AHpDqpyfFOhthyh:-N1mBL860UZEVUziT2nw:b-eoqb6z) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L121)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Does this condition start with the vehicle stopped?

I'd also recommend using the BasicAgentBehavior or the ConstantVelocityAgentBehavior, which is the more flexible Python agents 
</blockquote></details>

If using ConstantVelocityAgentBehavior, the ev might be too fast and crash onto ego. 
I try to set a init speed as 20 then use BasicAgentBehavior, it looks okay, but the ev might not be fast enough to pass ego. If I set a higher init speed, the ev might crash onto ego directly. 
Is there any way to have a fast enough agent that won't make a rear-end collision?
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 146 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c1Xeg6urVSd758cTx:-N1mBmOU85anJTdDmMcQ:b-lwpzz2) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L146)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This code is correct, but weird
</blockquote></details>

Optimized
___
*[`srunner/routes/YieldToEmergencyVehicle.xml` line 2 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1byadD06E4eqvlzVtI:-N1mBot41nyA64wWMBEe:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/routes/YieldToEmergencyVehicle.xml#L2)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I changed this. Please add this route to the leaderboard_2.0_testing.xml file instead. In that way, all testing rotues are at the same file, and we can more easily remove them later on. Just make sure the id doesn't match the other routes
</blockquote></details>

Done.
___
*[`srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py` line 1289 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1bz3v56m8lNFxZmeMS:-N1mBqLx5CRLcX0NpCwX:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenariomanager/scenarioatomics/atomic_trigger_conditions.py#L1289)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Not needed, we already have the atomic behavior Idle()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-12 06:23 UTC, glopezdiest requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 103 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c-At_EedV1czSE_Lt:-N1qsvpL38aJso0gtF64:b-rtr9g2) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L103)):*
<details><summary><i>Previously, TayYim (Tay Yim) wrote…</i></summary><blockquote>

Use trigger point as the reference waypoint when teleporting the EV(ev_start_transform). 
Do you mean it’s better to first spawn ev on  ev_start_transform, then move it underground, then teleport it back to ev_start_transform when the scenario is triggered?
</blockquote></details>

That's what we tend to do. Your appraoch is fine too
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 121 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c1AHpDqpyfFOhthyh:-N1qtbtN3H2witPdbBa5:b-2yklix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L121)):*
<details><summary><i>Previously, TayYim (Tay Yim) wrote…</i></summary><blockquote>

If using ConstantVelocityAgentBehavior, the ev might be too fast and crash onto ego. 
I try to set a init speed as 20 then use BasicAgentBehavior, it looks okay, but the ev might not be fast enough to pass ego. If I set a higher init speed, the ev might crash onto ego directly. 
Is there any way to have a fast enough agent that won't make a rear-end collision?
</blockquote></details>

You can create a new behavior that uses the BAsicAgent and dynamically changes its speed to a value higher than the ego's


<!-- Sent from Reviewable.io -->

2022-05-13 01:37 UTC, TayYim reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @glopezdiest)

___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 103 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c-At_EedV1czSE_Lt:-N1v2Ppu33xgoXfRjH_x:brfd2yv) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L103)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

That's what we tend to do. Your appraoch is fine too
</blockquote></details>

Changed. Spawn EV first on the ev_start_transform  to ensure validity.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 121 at r1](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N1c1AHpDqpyfFOhthyh:-N1v2fbn4Etxl83A6QZn:bfbo78y) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/4743e83566355f95f49699899dd43815bb1b898c/srunner/scenarios/yield_to_emergency_vehicle.py#L121)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

You can create a new behavior that uses the BAsicAgent and dynamically changes its speed to a value higher than the ego's
</blockquote></details>

Created a new behavior called FasterBasicAgentBehavior. Will set the actor's target speed higher than the other_actor's current speed


<!-- Sent from Reviewable.io -->

2022-05-20 07:49 UTC, glopezdiest commented
Some feedback after testing:

The **BasicAgent behavior** is a bit cluncky, and the EV can sometimes collide with the ego. Also, if the ego is too fast, the EV might never catch it. This is specially true for ambulances and firetrucks. Maybe you can use the `ConstantVelocityAgent`? That might be too unrealistic though, as it stops instantaneously.

The current version of the **YieldToEmergencyVehicleTest** will miss fail if the ego is faster than the EV and making it a total miss of hit with the 15 seconds is a bit weird. It just occured to me to do the following. What we care about is how much did the ego block the EV, so record the target speed and compare it to its actual one, how bad the ego did it is proportional to that value.

Lastly, after testing this I found out that scenario specific criteria were making the route stop (which shouldn't be the case) so I've updated the `leaderboard-2.0` branch

2022-05-20 08:57 UTC, TayYim commented
@glopezdiest 
> Maybe you can use the ConstantVelocityAgent? That might be too unrealistic though, as it stops instantaneously.

I've tried to do it. It shows that the EV will rear-end the ego initially if the ego is not that fast. I will try to make it work better anyway.

> What we care about is how much did the ego block the EV, so record the target speed and compare it to its actual one, how bad the ego did it is proportional to that value.

That make sense. Will try it. 

> Lastly, after testing this I found out that scenario specific criteria were making the route stop (which shouldn't be the case) so I've updated the leaderboard-2.0 branch

Yeah! I was confused about this, and I thought it was somehow a bug of the scenario before. Thanks for the fix.

2022-05-20 09:58 UTC, glopezdiest commented
I forgot to mention, add the special lights to the EV! Should be somethign like [this](https://github.com/carla-simulator/scenario_runner/blob/leaderboard-2.0/srunner/scenarios/background_activity.py#L1683)

2022-05-25 08:51 UTC, TayYim reviewed
Special lights were added.

Add AdaptiveConstantVelocityAgentBehavior, it will use blackboard to share target_speed with
YieldToEmergencyVehicleTest. YieldToEmergencyVehicleTest will record the speed of the EV every moment. When the scenario is over, it will calculate the mean_speed of the EV / target_speed to get a percentage, which will be the score.

An issue here is that background actors will be blocking the way when the EV goes far enough. It seems SwitchLane has not cleared them, and I don’t know why. Maybe it’s because the lane id is different there.

> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-:-N2uOwxk8Uvwu5A5E8Kw:bq98mzu)* status: 3 of 7 files reviewed, all discussions resolved (waiting on @glopezdiest)



<!-- Sent from Reviewable.io -->

2022-05-30 06:50 UTC, glopezdiest requested changes
> Reviewed 1 of 3 files at r4, 1 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 6 of 7 files reviewed, 10 unresolved discussions (waiting on @glopezdiest and @TayYim)

___
*[`srunner/scenariomanager/scenarioatomics/atomic_behaviors.py` line 2050 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IgpNU6psFtdNQlsja:-N3IgpNV97oI_bJYmGer:b-pdkhlm) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2050)):*
> ```Python
>         """Initialises the agent"""
>         # Get target speed
>         if self._reference_actor:
> ```

This check isn't really needed



_Code quote:_
```Python
if self._reference_actor:
```
___
*[`srunner/scenariomanager/scenarioatomics/atomic_criteria.py` line 2089 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IgwWWEpb6mfVFnexg:-N3IgwWWEpb6mfVFnexh:b-7aqi21) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L2089)):*
> ```Python
>             else:
>                 return new_status
>             
> ```

trailing whitespaces



_Code quote:_
```Python
············
```
___
*[`srunner/scenariomanager/scenarioatomics/atomic_criteria.py` line 2090 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IgyA373np3oPJkIbg:-N3IgyA373np3oPJkIbh:b-ovajrb) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L2090)):*
> ```Python
>                 return new_status
>             
>         if self._ev.is_alive:
> ```

Is this really needed



_Code quote:_
```Python
if self._ev.is_alive:
```
___
*[`srunner/scenariomanager/scenarioatomics/atomic_criteria.py` line 2108 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ih1Y-665Y_aPSfjdr:-N3Ih1Y-665Y_aPSfjds:bxwo7uy) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L2108)):*
> ```Python
>             self.test_status = "FAILURE"
> 
>         super().terminate(new_status)
> ```

Missing file endline



_Code quote:_
```Python
super().terminate(new_status)
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 47 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IhEmR6buCKXI9nvDl:-N3IhEmR6buCKXI9nvDm:b-4t6o7p) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L47)):*
> ```Python
>         self._ev_drive_distance = 1000 # m
> 
>         if 'emergency_vehicle_distance' in config.other_parameters:
> ```

I'd change this to just 'distance'



_Code quote:_
```Python
'emergency_vehicle_distance'
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 109 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ihb5r9oNe_VKpk-1D:-N3Ihb5r9oNe_VKpk-1E:btr3aes) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L109)):*
> ```Python
>         sequence = py_trees.composites.Sequence()
> 
>         sequence.add_child(SwitchLane(self._reference_waypoint.lane_id, False))
> ```

check if this is route mode



_Code quote:_
```Python
equence.
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 122 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IiM_ZDSUiwrgg3kj_:-N3IiM_ZDSUiwrgg3kja:b-tigrel) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L122)):*
> ```Python
> 
>         target_locations = self._reference_waypoint.next(self._ev_drive_distance)
>         target_location = target_locations[0].transform.location
> ```

This is weird, setting a target location at 1 Km away just so that it never ends. I suggest just not setting a plan for the agent, which will make them move forever



_Code quote:_
```Python
        target_locations = self._reference_waypoint.next(self._ev_drive_distance)
        target_location = target_locations[0].transform.location
        ev_end_condition.add_child(AdaptiveConstantVelocityAgentBehavior(
            self.other_actors[0], self.ego_vehicles[0], target_location, 15))
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 124 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IhuvS9gIxGJp_qDcT:-N3IhuvS9gIxGJp_qDcU:b-8hjwgm) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L124)):*
> ```Python
>         target_location = target_locations[0].transform.location
>         ev_end_condition.add_child(AdaptiveConstantVelocityAgentBehavior(
>             self.other_actors[0], self.ego_vehicles[0], target_location, 15))
> ```

Make this a varaible on initialization for better readibility of the scenario



_Code quote:_
```Python
15
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 131 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ii9KC7OskRhFb6b8U:-N3Ii9KC7OskRhFb6b8V:bddkq9u) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L131)):*
> ```Python
> 
>         # End condition
>         end_condition = py_trees.composites.Parallel("Waiting for ego driving for a certein distance",
> ```

Is this parallel needed?



_Code quote:_
```Python
        end_condition = py_trees.composites.Parallel("Waiting for ego driving for a certein distance",
                                                     policy=py_trees.common.ParallelPolicy.SUCCESS_ON_ONE)
```
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 138 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ii5xh5mEf5lqoG91M:-N3Ii5xh5mEf5lqoG91N:b-qmjldp) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L138)):*
> ```Python
>         sequence.add_child(end_condition)
> 
>         sequence.add_child(SwitchLane(self._reference_waypoint.lane_id, True))
> ```

Again, route mode only



_Code quote:_
```Python
sequence.add_child(SwitchLane(self._reference_waypoint.lane_id, True))
```


<!-- Sent from Reviewable.io -->

2022-06-01 03:20 UTC, TayYim reviewed
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 2 of 7 files reviewed, 10 unresolved discussions (waiting on @glopezdiest)

___
*[`srunner/scenariomanager/scenarioatomics/atomic_behaviors.py` line 2050 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IgpNU6psFtdNQlsja:-N3Ro1bH9E_FdF7r9A4J:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_behaviors.py#L2050)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This check isn't really needed
</blockquote></details>

Done.
___
*[`srunner/scenariomanager/scenarioatomics/atomic_criteria.py` line 2089 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IgwWWEpb6mfVFnexg:-N3RokQH0g6CCkIVj811:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L2089)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

trailing whitespaces
</blockquote></details>

Done.
___
*[`srunner/scenariomanager/scenarioatomics/atomic_criteria.py` line 2090 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IgyA373np3oPJkIbg:-N3SFGRw8oYVCHl4sJp2:b-rhnkyr) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L2090)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Is this really needed
</blockquote></details>

Yep. At the moment when EV is destroyed, the criterion is still running. An error like this will appear:
RuntimeError: trying to operate on a destroyed actor; an actor's function was called, but the actor is already destroyed.

With is_alive check, this can be avoided.
___
*[`srunner/scenariomanager/scenarioatomics/atomic_criteria.py` line 2108 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ih1Y-665Y_aPSfjdr:-N3RorTrA9EYseW41yDm:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenariomanager/scenarioatomics/atomic_criteria.py#L2108)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Missing file endline
</blockquote></details>

Done.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 47 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IhEmR6buCKXI9nvDl:-N3Rp3O9ENymBzslDjoT:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L47)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

I'd change this to just 'distance'
</blockquote></details>

Done.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 109 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ihb5r9oNe_VKpk-1D:-N3RpIVq8pWdUw_dIVEE:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L109)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

check if this is route mode
</blockquote></details>

Done.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 122 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IiM_ZDSUiwrgg3kj_:-N3RvSko2-_-f0aBk8hu:beaq985) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L122)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

This is weird, setting a target location at 1 Km away just so that it never ends. I suggest just not setting a plan for the agent, which will make them move forever
</blockquote></details>

I used to though that it's necessary to set a target location. Removed. The EV will follow the lane and never stop.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 124 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3IhuvS9gIxGJp_qDcT:-N3RprLs4nWv3eipwrE7:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L124)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Make this a varaible on initialization for better readibility of the scenario
</blockquote></details>

Done.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 131 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ii9KC7OskRhFb6b8U:-N3Rq0K_ApIlBoiAMUh_:b-wb9b6a) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L131)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Is this parallel needed?
</blockquote></details>

Not necessary I think. It's here because earlier the test will stop when a scenario with extra criteria is finished, so I add this to make some time. Removed.
___
*[`srunner/scenarios/yield_to_emergency_vehicle.py` line 138 at r6](https://reviewable.io/reviews/carla-simulator/scenario_runner/891#-N3Ii5xh5mEf5lqoG91M:-N3RpKw4CcbIS3zdigi_:b-896fix) ([raw file](https://github.com/carla-simulator/scenario_runner/blob/d148e97624c2ce479e67eabd0cc81aebbe308f45/srunner/scenarios/yield_to_emergency_vehicle.py#L138)):*
<details><summary><i>Previously, glopezdiest wrote…</i></summary><blockquote>

Again, route mode only
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-02 06:14 UTC, glopezdiest reviewed
> Reviewed 1 of 3 files at r7, 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @glopezdiest)



<!-- Sent from Reviewable.io -->

2022-06-02 06:14 UTC, glopezdiest approved these changes
> Reviewed 2 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/carla-simulator/scenario_runner/891)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TayYim)



<!-- Sent from Reviewable.io -->

2022-06-02 06:15 UTC, merged